apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs-app.fullname" . }}
  labels:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: nodejs-app
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
